SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[_KJ_MAAK_NIEUW_DATABASE_TABEL]  
@TABLENAME NVARCHAR(255)
AS
BEGIN
	DECLARE @SQL NVARCHAR(MAX) 
	
	--STAP 1 - MAAK TABEL AAN
	BEGIN TRANSACTION		

		SET @SQL = N'
				CREATE TABLE [dbo].['+@TABLENAME+'](
					[ID] [int] IDENTITY(1,1) NOT NULL,
					[TS_CREATED] [datetime] NOT NULL,
					[TS_LASTMODIFIED] [datetime] NULL,
					[ACTIVE] [bit] NOT NULL
				 CONSTRAINT [PK_'+@TABLENAME+'] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY]'
		EXECUTE sp_executesql @SQL		

		SET @SQL = N'ALTER TABLE [dbo].['+@TABLENAME+'] ADD  CONSTRAINT [DF_'+@TABLENAME+'_TS_CREATED]  DEFAULT (getdate()) FOR [TS_CREATED]'
		EXECUTE sp_executesql @SQL
				
		SET @SQL = N'ALTER TABLE [dbo].['+@TABLENAME+'] ADD  CONSTRAINT [DF_'+@TABLENAME+'_TS_LASTMODIFIED]  DEFAULT (getdate()) FOR [TS_LASTMODIFIED]'
		EXECUTE sp_executesql @SQL

		SET @SQL = N'ALTER TABLE [dbo].['+@TABLENAME+'] ADD  CONSTRAINT [DF_'+@TABLENAME+'_ACTIVE]  DEFAULT ((1)) FOR [ACTIVE]'
		EXECUTE sp_executesql @SQL
		

	COMMIT TRANSACTION

	--STAP 2 - MAAK DEFAULT TRIGGER AAN
	BEGIN TRANSACTION

		SET @SQL =
			N'
				CREATE TRIGGER [dbo].[TR_'+@TABLENAME+'_TS_LASTMODIFIED]
						   ON  [dbo].['+@TABLENAME+']
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								'+@TABLENAME+' T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END'
		EXECUTE sp_executesql @SQL	
		
		SET @SQL = 'ALTER TABLE [dbo].['+@TABLENAME+'] ENABLE TRIGGER [TR_'+@TABLENAME+'_TS_LASTMODIFIED]'
		EXECUTE sp_executesql @SQL	

	COMMIT TRANSACTION
	

END
GO
