SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[REPORT_INVOICE_VAT]
	@FK_FINANCE_INVOICE INT
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		FIL.FK_FINANCE_VAT,
		FV.[PERCENTAGE],
		FV.[DESCRIPTION],
		SUM(FIL.PRICE_TOTAL) AS TOTAL_EXCL,
		SUM(FIL.VAT_TOTAL) AS VAT_TOTAL,
		SUM(FIL.PRICE_TOTAL_INCVAT) AS TOTAL_INCL
	FROM FINANCE_INVOICE_LINE FIL WITH (NOLOCK)
	JOIN FINANCE_VAT FV WITH (NOLOCK) ON FV.ID = FIL.FK_FINANCE_VAT
	WHERE FIL.FK_FINANCE_INVOICE = @FK_FINANCE_INVOICE
	  AND FIL.ACTIVE = 1
	GROUP BY FIL.FK_FINANCE_VAT, FV.[PERCENTAGE], FV.[DESCRIPTION]
	ORDER BY FV.[PERCENTAGE] ASC

END
GO
