SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[FINANCE_ACCOUNTANCY_INVOICE_ITEM]
	@PK_FINANCE_INVOICE INT
AS
BEGIN
/* OMSCHRIJVING ********************************************************************************************************************************
 * 
 * VAT_TYPE:
 * - V (Sales basis)
 * - X (Credit note sales basis)
 * - A (Sales VAT to pay)
 * - Z (Credit note sales VAT to claim)
 **********************************************************************************************************************************************/
	SET NOCOUNT ON;

	SELECT 
		FI.DATE,
		IIF(FI.PRICE_TOTAL_INCL < 0, 'X', 'V') AS [VAT_TYPE],
		YEAR(FI.DATE) AS [FINANCIAL_YEAR],
		MONTH(FI.DATE) AS [FINANCIAL_PERIOD],
		FI.EXPIRATION_DATE AS [DUE_DATE],
		FIL.DESCRIPTION,
		CR.NUMBER_DEBTOR,
		FIL.PRICE_TOTAL AS [AMOUNT_DC],
		FIL.VAT_TOTAL AS [AMOUNT_VAT_DC],
		FIL.PRICE_TOTAL AS [AMOUNT_VAT_BASE_DC],
		FV.VATCODE,
		FV.PERCENTAGE,
		FL.ACCOUNT AS [GL_ACCOUNT_CODE]
	FROM FINANCE_INVOICE_LINE FIL WITH (NOLOCK)
	LEFT JOIN FINANCE_VAT FV WITH (NOLOCK) ON FV.ID = FIL.FK_FINANCE_VAT
	LEFT JOIN FINANCE_LEDGER FL WITH (NOLOCK) ON FL.ID = FIL.FK_FINANCE_LEDGER
	JOIN FINANCE_INVOICE FI WITH (NOLOCK) ON FI.ID = FIL.FK_FINANCE_INVOICE
	JOIN CRM_RELATION CR WITH (NOLOCK) ON CR.ID = FI.FK_CRM_RELATION
	WHERE FIL.FK_FINANCE_INVOICE = @PK_FINANCE_INVOICE

	--UNION ALL

	--SELECT
	--	FI.DATE,
	--	IIF(FI.SALEPRICEINCVAT < 0, 'Z', 'A') AS [VAT_TYPE],
	--	YEAR(FI.DATE) AS [FINANCIAL_YEAR],
	--	MONTH(FI.DATE) AS [FINANCIAL_PERIOD],
	--	FI.EXPIRATION_DATE AS [DUE_DATE],
	--	FV.DESCRIPTION AS DESCRIPTION,
	--	CR.DEBTORNUMBER,
	--	SUM(FII.SALEPRICEINCVATTOTAL) - SUM(FII.SALEPRICETOTAL) AS [AMOUNT_DC],
	--	SUM(FII.SALEPRICEINCVATTOTAL) - SUM(FII.SALEPRICETOTAL) AS [AMOUNT_VAT_DC],
	--	SUM(FII.SALEPRICETOTAL) AS [AMOUNT_VAT_BASE_DC],
	--	FV.VATCODE,
	--	FV.PERCENTAGE,
	--	FL.ACCOUNT AS [GL_ACCOUNT_CODE]
	--FROM FINANCE_INVOICE_ITEM FII WITH (NOLOCK) 
	--LEFT JOIN FINANCE_VAT FV WITH (NOLOCK) ON FV.ID = FII.FK_FINANCE_VAT
	--LEFT JOIN FINANCE_LEDGER FL WITH (NOLOCK) ON FL.ID = FV.FK_FINANCE_LEDGER_CONTRAACCOUNT
	--JOIN FINANCE_INVOICE FI WITH (NOLOCK) ON FI.ID = FII.FK_FINANCE_INVOICE
	--JOIN CRM_RELATION CR WITH (NOLOCK) ON CR.ID = FI.FK_CRM_RELATION
	--WHERE FII.FK_FINANCE_INVOICE = @PK_FINANCE_INVOICE 
	--GROUP BY 
	--	/* INVOICE */ FI.DATE, FI.SALEPRICEINCVAT, FI.EXPIRATION_DATE, CR.DEBTORNUMBER,
	--	/* VAT/LEDGER */ FV.VATCODE, FV.PERCENTAGE, FL.ACCOUNT, FV.DESCRIPTION

END
GO
