SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PROJECT_CALCULATE_INVOICING_COMPLETE]
	@FK_PROJECT INT
AS
BEGIN

	DECLARE @INVOICED BIT

	-- Deterimine fullyy invoiced based on sub project rows
	-- Producten
	SET @INVOICED = ISNULL((
		SELECT
			IIF(
				SUM(IIF(FI.FK_CORE_WORKFLOWSTATE = [dbo].[CORE_WORKFLOWSTATE_INVOICE_FINAL](), 1, 0)) = COUNT(1),
				1,
				0
			)
		FROM FINANCE_INVOICE_SCHEME FIS WITH (NOLOCK)
		JOIN PROJECT_ASSORTMENT_PRODUCT PAP WITH (NOLOCK) ON PAP.ID = FIS.FK_PROJECT_ASSORTMENT_PRODUCT
		LEFT JOIN FINANCE_INVOICE_LINE FIL WITH (NOLOCK) ON FIL.ID = FIS.FK_FINANCE_INVOICE_LINE
		LEFT JOIN FINANCE_INVOICE FI WITH (NOLOCK) ON FI.ID = FIL.FK_FINANCE_INVOICE
		WHERE PAP.FK_PROJECT = @FK_PROJECT
			AND PAP.ACTIVE = 1
			AND FIS.ACTIVE = 1
	), 0)

	-- Update on project
	UPDATE PROJECT SET
	  INVOICING_COMPLETE = @INVOICED
	WHERE ID = @FK_PROJECT

END
GO
