SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[FINANCE_INVOICE_RECALCULATE_TOTALS]
	@FK_FINANCE_INVOICE INT
AS
BEGIN

	UPDATE FI SET
	  PRICE_TOTAL_EXCL = LINES.PRICE_TOTAL,
	  VAT_TOTAL = LINES.VAT_TOTAL,
	  PRICE_TOTAL_INCL = LINES.PRICE_TOTAL_INCVAT
	FROM FINANCE_INVOICE FI
	OUTER APPLY (
		SELECT
			SUM(FIL.PRICE_TOTAL) AS PRICE_TOTAL,
			SUM(FIL.VAT_TOTAL) AS VAT_TOTAL,
			SUM(FIL.PRICE_TOTAL_INCVAT) AS PRICE_TOTAL_INCVAT
		FROM FINANCE_INVOICE_LINE FIL WITH (NOLOCK)
		WHERE FIL.FK_FINANCE_INVOICE = FI.ID
		  AND FIL.ACTIVE = 1
	) LINES
	WHERE FI.ID = @FK_FINANCE_INVOICE

END
GO
