SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[FINANCE_INVOICE_RECALCULATE_SPECIFICATION]
	@FK_FINANCE_INVOICE INT
AS
BEGIN

	DECLARE @HAS_SPECIFICATION BIT = (
		SELECT 
			CAST(ISNULL(MAX(CAST(SHOW_ON_SPECIFICATION AS INT)), 0) AS BIT) 
		FROM FINANCE_INVOICE_LINE FIL WITH (NOLOCK)
		WHERE FIL.FK_FINANCE_INVOICE = @FK_FINANCE_INVOICE
	)

	UPDATE FINANCE_INVOICE SET
	  HAS_SPECIFICATION = @HAS_SPECIFICATION
	WHERE ID = @FK_FINANCE_INVOICE

END
GO
