SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[FINANCE_BILLCHECK_FILL]
	 @DATE DATE 
AS
BEGIN
	-- Datum tabel vooruit populaten, 2 jaar terug, 2 jaar vooruit
	DECLARE @PopFrom DATE = DATEADD(MONTH,-24,GETDATE()), 
			@PopTo DATE = DATEADD(MONTH,24,GETDATE())

	EXEC dbo.POPULATE_DATES @PopFrom, @PopTo
	
	-- Alle oude data verwijderen
	DELETE FROM FINANCE_BILLCHECK

	-- PRODUCTEN
	INSERT INTO [FINANCE_BILLCHECK] (
		[FK_CORE_LABEL],
		[FK_PROJECT],
		[FK_CRM_RELATION],
		[FK_CRM_RELATION_ADDRESS],
		[FK_CRM_CONTACT],
		[FK_FINANCE_VAT],
		[FK_FINANCE_LEDGER],
		[FK_PROJECT_ASSORTMENT_PRODUCT],
		[FK_FINANCE_INVOICE_COLLECT_INTERVAL],
		[QUANTITY],
		[PRICE],
		[DESCRIPTION]
	)
	SELECT
		P.FK_CORE_LABEL,
		P.ID,
		CR.ID,
NULL,--		P.FK_CRM_RELATION_ADDRESS,
NULL,--		COALESCE(P.FK_CRM_CONTACT_INVOICE, CR.FK_CRM_CONTACT_FINANCE, P.FK_CRM_CONTACT),
		IIF(CR.VAT_LIABLE = 1, AP.FK_FINANCE_VAT, CL.FK_FINANCE_VAT_SHIFTED),
		AP.FK_FINANCE_LEDGER,
		PAP.ID,
		ISNULL(CR.FK_FINANCE_INVOICE_COLLECT_INTERVAL, [dbo].[FINANCE_INVOICE_COLLECT_INTERVAL_SEPARATED]()),
		PAP.QUANTITY AS [QUANTITY],
		PAP.PRICE,
		AP.DESCRIPTION_EXT
	FROM PROJECT_ASSORTMENT_PRODUCT PAP WITH (NOLOCK)
	JOIN PROJECT P WITH (NOLOCK) ON P.ID = PAP.FK_PROJECT
	LEFT JOIN CORE_LABEL CL WITH (NOLOCK) ON CL.ID = P.FK_CORE_LABEL
	JOIN CRM_RELATION CR WITH (NOLOCK) ON CR.ID = P.FK_CRM_RELATION_REFERRER
	LEFT JOIN ASSORTMENT_PRODUCT AP WITH (NOLOCK) ON AP.ID = PAP.FK_ASSORTMENT_PRODUCT
	WHERE PAP.ACTIVE = 1
	  AND P.ACTIVE = 1
	  AND PAP.FK_FINANCE_INVOICE_LINE IS NULL
	  AND AP.FK_ASSORTMENT_PRODUCT_TYPE = [dbo].[ASSORTMENT_PRODUCT_TYPE_PRODUCT]()


	-- MARK EVERYTHING AS UNCHECKED FOR BILLING
	UPDATE FINANCE_BILLCHECK SET 
	  DO_BILL = 0 
	WHERE DO_BILL IS NULL

END
GO
