SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[DATE_FRACTION_BETWEENDATES](@DATE DATE, @ENDDATE DATE)
RETURNS DECIMAL(10,2)
AS
BEGIN

	DECLARE @SwitchEndDate DATE, @SwitchStartDate DATE, @Factor INT = 1
	IF(@ENDDATE < @DATE)
	BEGIN
		SELECT @SwitchStartDate = @DATE, @SwitchEndDate = @ENDDATE
		SELECT @DATE = @SwitchEndDate, @ENDDATE = @SwitchStartDate, @Factor = -1    
	END

	RETURN (
		SELECT ROUND(SUM(FRACTION),2) * @Factor 
		FROM DATES D WITH(NOLOCK) 
		WHERE [DATE] >= @DATE 
		  AND [DATE] <= @ENDDATE
	)
END


GO
