SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[EFFICIENCY](
	@COST DECIMAL(15,6), 
	@REVENUE DECIMAL(15,6)
) 
RETURNS DECIMAL(15, 6)
AS
BEGIN

	RETURN(CASE
		WHEN ISNULL(ROUND(@REVENUE,2),0) > 0 THEN 
			(@REVENUE - @COST) / @REVENUE
		WHEN ISNULL(ROUND(@REVENUE,2),0) = 0 AND ISNULL(ROUND(@COST,2),0) = 0 THEN 
			0
		WHEN ISNULL(ROUND(@REVENUE,2),0) = 0 AND ISNULL(ROUND(@COST,2),0) <> 0 THEN 
			-1
		WHEN @REVENUE IS NULL THEN
			NULL
		WHEN ISNULL(ROUND(@REVENUE,2),0) < 0 AND ISNULL(ROUND(@COST,2),0) = 0 THEN 
			NULL
		ELSE
			-1
	END * 100)

END
GO
