SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[DATE_FRACTION_QUARTER_END](@DATE DATE)
RETURNS DATE
AS
BEGIN
	RETURN (
		SELECT MAX(DATE) 
		FROM DATES D WITH(NOLOCK) 
		WHERE D.[YEAR] = YEAR(@DATE) 
		  AND D.[QUARTER] =  DATEPART(q, @DATE)
	)
END
GO
