SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[CRM_CONTACT_PARENT_ACTIVE](@FK_CRM_RELATION INT) 
RETURNS INT AS 
BEGIN 

DECLARE @RESULT BIT = CAST(1 AS BIT)

IF @FK_CRM_RELATION > 0
	SET @RESULT = (SELECT TOP 1 ACTIVE FROM CRM_RELATION WITH (NOLOCK) WHERE ID = @FK_CRM_RELATION)

RETURN @RESULT
	
END 
GO
