SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[V_TL_CORE_COUNTRY](@PK_LANGUAGE INT=1)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		CORE_COUNTRY.*
		,TL_COUNTRYNAME.TEXT AS TL_COUNTRYNAME_TEXT

	FROM 
		CORE_COUNTRY
		LEFT JOIN dbo.[V_CORE_TRANSLATION_LANGUAGE](@PK_LANGUAGE) TL_COUNTRYNAME ON TL_COUNTRYNAME.ID = CORE_COUNTRY.TL_COUNTRYNAME

)
GO
