SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[V_TL_CORE_DROPDOWNVALUE](@PK_LANGUAGE INT=1)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		CORE_DROPDOWNVALUE.*
		,TL_VALUE.TEXT AS TL_VALUE_TEXT

	FROM 
		CORE_DROPDOWNVALUE
		LEFT JOIN dbo.[V_CORE_TRANSLATION_LANGUAGE](@PK_LANGUAGE) TL_VALUE ON TL_VALUE.ID = CORE_DROPDOWNVALUE.TL_VALUE

)


GO
