CREATE TABLE [dbo].[ASSORTMENT_PRODUCT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_ASSORTMENT_PRODUCT_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_ASSORTMENT_PRODUCT_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_ASSORTMENT_PRODUCT_ACTIVE] DEFAULT ((1)),
[FK_FINANCE_VAT] [int] NULL,
[FK_FINANCE_LEDGER] [int] NULL,
[DESCRIPTION_INT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION_EXT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRICE] [decimal] (30, 15) NULL,
[PRICE_INCVAT] [decimal] (30, 15) NULL,
[FK_DOCUMENT] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_ASSORTMENT_PRODUCT_PRICE]
ON  [dbo].[ASSORTMENT_PRODUCT]
AFTER UPDATE, INSERT
AS 
BEGIN
SET NOCOUNT ON;
 
	IF UPDATE(PRICE) OR UPDATE(FK_FINANCE_VAT)
	BEGIN
		UPDATE FN SET 
			FN.PRICE_INCVAT = ROUND((
				I.PRICE * ((1)+isnull(V.PERCENTAGE,(0))/(100))				
			), 2)
		FROM  ASSORTMENT_PRODUCT FN
		INNER JOIN INSERTED I ON FN.ID = I.ID
		LEFT OUTER JOIN FINANCE_VAT V ON V.ID = FN.FK_FINANCE_VAT
	END

END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_ASSORTMENT_PRODUCT_TS_LASTMODIFIED]
						   ON  [dbo].[ASSORTMENT_PRODUCT]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								ASSORTMENT_PRODUCT T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[ASSORTMENT_PRODUCT] ADD CONSTRAINT [PK_ASSORTMENT_PRODUCT] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASSORTMENT_PRODUCT] ADD CONSTRAINT [FK_ASSORTMENT_PRODUCT_DOCUMENT] FOREIGN KEY ([FK_DOCUMENT]) REFERENCES [dbo].[DOCUMENT] ([ID])
GO
ALTER TABLE [dbo].[ASSORTMENT_PRODUCT] ADD CONSTRAINT [FK_ASSORTMENT_PRODUCT_FINANCE_LEDGER] FOREIGN KEY ([FK_FINANCE_LEDGER]) REFERENCES [dbo].[FINANCE_LEDGER] ([ID])
GO
ALTER TABLE [dbo].[ASSORTMENT_PRODUCT] ADD CONSTRAINT [FK_ASSORTMENT_PRODUCT_FINANCE_VAT] FOREIGN KEY ([FK_FINANCE_VAT]) REFERENCES [dbo].[FINANCE_VAT] ([ID])
GO
