CREATE TABLE [dbo].[DOCUMENT_LOG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_DOCUMENT_LOG_ACTIVE] DEFAULT ((1)),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_DOCUMENT_LOG_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_DOCUMENT_LOG_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_DOCUMENT] [int] NULL,
[DESCRIPTION] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJECT] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJECT_ID] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[TR_DOCUMENT_LOG_TS_LASTMODIFIED]
		   ON  [dbo].[DOCUMENT_LOG]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				DOCUMENT_LOG  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[DOCUMENT_LOG] ADD CONSTRAINT [PK_DOCUMENT_LOG] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOCUMENT_LOG] ADD CONSTRAINT [FK_DOCUMENT_LOG_DOCUMENT] FOREIGN KEY ([FK_DOCUMENT]) REFERENCES [dbo].[DOCUMENT] ([ID])
GO
