CREATE TABLE [dbo].[ASSORTMENT_PRODUCT_TYPE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_ASSORTMENT_PRODUCT_TYPE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_ASSORTMENT_PRODUCT_TYPE_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_ASSORTMENT_PRODUCT_TYPE_ACTIVE] DEFAULT ((1)),
[DESCRIPTION] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

				CREATE TRIGGER [dbo].[TR_ASSORTMENT_PRODUCT_TYPE_TS_LASTMODIFIED]
						   ON  [dbo].[ASSORTMENT_PRODUCT_TYPE]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								ASSORTMENT_PRODUCT_TYPE T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[ASSORTMENT_PRODUCT_TYPE] ADD CONSTRAINT [PK_ASSORTMENT_PRODUCT_TYPE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
