CREATE TABLE [dbo].[CORE_FILE_REQUEST]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_FILE_REQUEST_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_FILE_REQUEST_TS_LASTMODIFIED] DEFAULT (getdate()),
[OBJECT] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OBJECT_ID] [int] NOT NULL,
[FILENAME] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TOKEN] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CORE_FILE_REQUEST_TOKEN] DEFAULT (newid()),
[EXPIRES_AT] [datetime] NULL CONSTRAINT [DF_CORE_FILE_REQUEST_EXPIRES_AT] DEFAULT (dateadd(minute,(15),getdate())),
[DOWNLOADED] [bit] NULL CONSTRAINT [DF_CORE_FILE_REQUEST_DOWNLOADED] DEFAULT ((0)),
[UPLOADED] [bit] NULL CONSTRAINT [DF_CORE_FILE_REQUEST_UPLOADED] DEFAULT ((0)),
[REQUEST_OBJECT] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REQUEST_OBJECT_ID] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_FILE_REQUEST_LOG]
	ON  [dbo].[CORE_FILE_REQUEST]
	AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	IF UPDATE(DOWNLOADED)
	BEGIN

		INSERT INTO DOCUMENT_LOG (
		    ACTIVE,
		    FK_DOCUMENT,
		    DESCRIPTION,
			[OBJECT],
			[OBJECT_ID]
		)
		SELECT
			1,
			I.[OBJECT_ID],
			'Downloaded',
			I.REQUEST_OBJECT,
			I.REQUEST_OBJECT_ID
		FROM INSERTED I

	END

	IF UPDATE(UPLOADED)
	BEGIN

		INSERT INTO DOCUMENT_LOG (
		    ACTIVE,
		    FK_DOCUMENT,
		    DESCRIPTION,
			[OBJECT],
			[OBJECT_ID]
		)
		SELECT
			1,
			I.[OBJECT_ID],
			'Uploaded',
			I.REQUEST_OBJECT,
			I.REQUEST_OBJECT_ID
		FROM INSERTED I

	END

END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[TR_CORE_FILE_REQUEST_TS_LASTMODIFIED]
		   ON  [dbo].[CORE_FILE_REQUEST]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				CORE_FILE_REQUEST  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[CORE_FILE_REQUEST] ADD CONSTRAINT [PK_CORE_FILE_REQUEST] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
