CREATE TABLE [dbo].[CONTACT_MOMENT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CONTACT_MOMENT_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CONTACT_MOMENT_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CONTACT_MOMENT_ACTIVE] DEFAULT ((1)),
[FK_CORE_USER_CREATED] [int] NOT NULL,
[FK_PROJECT] [int] NULL,
[DATE] [datetime] NOT NULL,
[FK_CRM_CONTACT] [int] NULL,
[FK_CORE_DROPDOWNVALUE_TYPE] [int] NULL,
[FK_CORE_DROPDOWNVALUE_CATEGORY] [int] NULL,
[SUBJECT] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTENT] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CONTACT_MOMENT_TS_LASTMODIFIED]
						   ON  [dbo].[CONTACT_MOMENT]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								CONTACT_MOMENT T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[CONTACT_MOMENT] ADD CONSTRAINT [PK_CONTACT_MOMENT] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTACT_MOMENT] ADD CONSTRAINT [FK_CONTACT_MOMENT_CORE_DROPDOWNVALUE] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_CATEGORY]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CONTACT_MOMENT] ADD CONSTRAINT [FK_CONTACT_MOMENT_CORE_DROPDOWNVALUE1] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_TYPE]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CONTACT_MOMENT] ADD CONSTRAINT [FK_CONTACT_MOMENT_CORE_USER] FOREIGN KEY ([FK_CORE_USER_CREATED]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[CONTACT_MOMENT] ADD CONSTRAINT [FK_CONTACT_MOMENT_CRM_CONTACT] FOREIGN KEY ([FK_CRM_CONTACT]) REFERENCES [dbo].[CRM_CONTACT] ([ID])
GO
ALTER TABLE [dbo].[CONTACT_MOMENT] ADD CONSTRAINT [FK_CONTACT_MOMENT_PROJECT] FOREIGN KEY ([FK_PROJECT]) REFERENCES [dbo].[PROJECT] ([ID])
GO
