CREATE TABLE [dbo].[DATES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_DATES_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_DATES_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_DATES_ACTIVE] DEFAULT ((1)),
[DATE] [date] NULL,
[YEAR] [int] NULL,
[MONTH] [int] NULL,
[DAY] [int] NULL,
[DAY_NUMBER] [int] NULL,
[WEEK_NUMBER] [int] NULL,
[EVEN_WEEK] [bit] NULL,
[START_OF_WEEK] [date] NULL,
[END_OF_WEEK] [date] NULL,
[IS_START_OF_WEEK] [bit] NULL,
[IS_END_OF_WEEK] [bit] NULL,
[IS_START_OF_MONTH] [bit] NULL,
[IS_END_OF_MONTH] [bit] NULL,
[FRACTION] [numeric] (38, 30) NULL,
[QUARTER] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

				CREATE TRIGGER [dbo].[TR_DATES_TS_LASTMODIFIED]
						   ON  [dbo].[DATES]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								DATES T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[DATES] ADD CONSTRAINT [PK_DATES] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
