CREATE TABLE [dbo].[CORE_ROLE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_ROLE_ACTIVE_1] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_ROLE_TS_CREATED_1] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_ROLE_TS_LASTMODIFIED_1] DEFAULT (getdate()),
[DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_ROLE] ADD CONSTRAINT [PK_CORE_ROLE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
