CREATE TABLE [dbo].[CORE_WORKFLOWSTATE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_WORKFLOWSTATE_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_WORKFLOWSTATE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_WORKFLOWSTATE_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CORE_WORKFLOWSTATETYPE] [int] NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTION_DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE_COLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE_ICON] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_WORKFLOWSTATE_TRANSLATION]
		   ON  [dbo].[CORE_WORKFLOWSTATE]
		   AFTER INSERT , UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			IF TRIGGER_NESTLEVEL() <= 1
			BEGIN

				--VOOR ELKE ROW DIE INGEVOERD IS, DE SP CORE_TRANSLATION_FILLFIELDS AANROEPEN
				DECLARE @TABLENAME NVARCHAR(150) 

				SELECT @TABLENAME = OBJECT_NAME(parent_object_id) 
							FROM sys.objects 
							WHERE sys.objects.name = OBJECT_NAME(@@PROCID)
			
				EXEC CORE_TRANSLATION_CHECKFULLTABLE @TABLENAME
		
			END
		END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_WORKFLOWSTATE_TS_LASTMODIFIED]
		   ON  [dbo].[CORE_WORKFLOWSTATE]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				CORE_WORKFLOWSTATE  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[CORE_WORKFLOWSTATE] ADD CONSTRAINT [PK_CORE_WORKFLOWSTATE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_WORKFLOWSTATE] ADD CONSTRAINT [FK_CORE_WORKFLOWSTATE_CORE_WORKFLOWSTATETYPE] FOREIGN KEY ([FK_CORE_WORKFLOWSTATETYPE]) REFERENCES [dbo].[CORE_WORKFLOWSTATETYPE] ([ID])
GO
