CREATE TABLE [dbo].[CORE_DROPDOWNTYPE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_DROPDOWNTYPE_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_DROPDOWNTYPE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_DROPDOWNTYPE_TS_LASTMODIFIED] DEFAULT (getdate()),
[DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


		CREATE TRIGGER [dbo].[TR_CORE_DROPDOWNTYPE_TS_LASTMODIFIED]
		   ON  [dbo].[CORE_DROPDOWNTYPE]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				CORE_DROPDOWNTYPE  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
		
GO
ALTER TABLE [dbo].[CORE_DROPDOWNTYPE] ADD CONSTRAINT [PK_CORE_DROPDOWNTYPE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
