CREATE TABLE [dbo].[CORE_SETTING_TYPE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_SETTING_TYPE_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_SETTING_TYPE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_SETTING_TYPE_TS_LASTMODIFIED] DEFAULT (getdate()),
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FIELD_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[TR_CORE_SETTING_TYPE_TS_LASTMODIFIED]
	ON  [dbo].[CORE_SETTING_TYPE]
	AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	UPDATE T SET 
		T.TS_LASTMODIFIED = GETDATE()
	FROM 
		CORE_SETTING_TYPE T
	INNER JOIN INSERTED I ON T.ID = I.ID
END
GO
ALTER TABLE [dbo].[CORE_SETTING_TYPE] ADD CONSTRAINT [PK_CORE_SETTING_TYPE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
