CREATE TABLE [dbo].[TASK]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_TASK_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_TASK_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_TASK_ACTIVE] DEFAULT ((1)),
[FK_CORE_USER_CREATED] [int] NOT NULL,
[FK_CORE_USER_ASSIGNEE] [int] NULL,
[FK_CORE_USER_STARTED] [int] NULL,
[FK_CORE_USER_DONE] [int] NULL,
[FK_CRM_RELATION] [int] NULL,
[FK_PROJECT] [int] NULL,
[FK_TASK_LIST] [int] NULL,
[FK_ASSORTMENT_PRODUCT] [int] NULL,
[FK_PROJECT_ASSORTMENT_PRODUCT] [int] NULL,
[DEADLINE] [date] NULL,
[REMINDER_DATE] [datetime] NULL,
[SUBJECT] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTENT] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STARTED] [bit] NULL CONSTRAINT [DF_TASK_STARTED] DEFAULT ((0)),
[STARTED_DATE] [datetime] NULL,
[DONE] [bit] NOT NULL CONSTRAINT [DF_TASK_DONE] DEFAULT ((0)),
[DONE_DATE] [datetime] NULL,
[REMEMBER_DATES] [int] NULL,
[EXPIRATION_DATES] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_TASK_TS_LASTMODIFIED]
						   ON  [dbo].[TASK]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								TASK T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [PK_TASK] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_ASSORTMENT_PRODUCT] FOREIGN KEY ([FK_ASSORTMENT_PRODUCT]) REFERENCES [dbo].[ASSORTMENT_PRODUCT] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_CONTACT_MOMENT] FOREIGN KEY ([FK_TASK_LIST]) REFERENCES [dbo].[STANDARD_TASK_LIST] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_CORE_USER] FOREIGN KEY ([FK_CORE_USER_CREATED]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_CORE_USER1] FOREIGN KEY ([FK_CORE_USER_ASSIGNEE]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_CORE_USER2] FOREIGN KEY ([FK_CORE_USER_DONE]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_CORE_USER3] FOREIGN KEY ([FK_CORE_USER_STARTED]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_CRM_RELATION] FOREIGN KEY ([FK_CRM_RELATION]) REFERENCES [dbo].[CRM_RELATION] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_PROJECT] FOREIGN KEY ([FK_PROJECT]) REFERENCES [dbo].[PROJECT] ([ID])
GO
ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_PROJECT_ASSORTMENT_PRODUCT] FOREIGN KEY ([FK_PROJECT_ASSORTMENT_PRODUCT]) REFERENCES [dbo].[PROJECT_ASSORTMENT_PRODUCT] ([ID])
GO
