CREATE TABLE [dbo].[FINANCE_PAYMENT_TERM]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_FINANCE_PAYMENT_TERM_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_FINANCE_PAYMENT_TERM_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_FINANCE_PAYMENT_TERM_ACTIVE] DEFAULT ((1)),
[FK_CORE_LABEL] [int] NULL,
[CODE] [int] NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMOUNT_DAYS] [int] NULL,
[DEFAULT] [bit] NULL CONSTRAINT [DF_FINANCE_PAYMENT_TERM_DEFAULT] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_FINANCE_PAYMENT_TERM_TS_LASTMODIFIED]
						   ON  [dbo].[FINANCE_PAYMENT_TERM]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								FINANCE_PAYMENT_TERM T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[FINANCE_PAYMENT_TERM] ADD CONSTRAINT [PK_FINANCE_PAYMENT_TERM] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FINANCE_PAYMENT_TERM] ADD CONSTRAINT [FK_FINANCE_PAYMENT_TERM_CORE_LABEL] FOREIGN KEY ([FK_CORE_LABEL]) REFERENCES [dbo].[CORE_LABEL] ([ID])
GO
