CREATE TABLE [dbo].[CRM_CONTACT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CRM_CONTACT_ACTIVE] DEFAULT ((1)),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CRM_CONTACT_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CRM_CONTACT_TS_LASTMODIFIED] DEFAULT (getdate()),
[CLIENT_ACTIVE] AS ([dbo].[CRM_CONTACT_PARENT_ACTIVE]([FK_CRM_RELATION])),
[FK_CRM_RELATION] [int] NULL,
[FK_CORE_DROPDOWNVALUE_SALUTATION] [int] NULL,
[FK_CORE_DROPDOWNVALUE_GENDER] [int] NULL,
[FK_CORE_DROPDOWNVALUE_ATTN] [int] NULL,
[INITIALS] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREPOSITION] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PHONENUMBER] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELLPHONENUMBER] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAILADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PASSWORD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMEMBER_TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULLNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULLNAME_ATTN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTHDAY_DATE] [datetime] NULL,
[REMARKS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEW_PASSWORD] [datetime] NULL,
[DOCUMENT_PASSWORD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOCUMENT_REMEMBER_TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CRM_CONTACT_FULLNAME]
	ON  [dbo].[CRM_CONTACT]
	AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	SET CONCAT_NULL_YIELDS_NULL ON;
	SET ARITHABORT ON;

	IF UPDATE (FIRSTNAME) OR UPDATE (PREPOSITION) OR UPDATE (LASTNAME) 
    BEGIN
		UPDATE FN SET 
		  FN.FULLNAME = ISNULL(LTRIM(RTRIM(FN.FIRSTNAME)) + ' ', '') +
						ISNULL(LTRIM(RTRIM(NULLIF(FN.PREPOSITION,''))) + ' ', '') + 
						ISNULL(LTRIM(RTRIM(FN.LASTNAME)),'')
		FROM 
			CRM_CONTACT FN
		INNER JOIN INSERTED I ON FN.ID = I.ID
	END
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CRM_CONTACT_FULLNAME_ATTN]
	ON  [dbo].[CRM_CONTACT]
	AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	SET CONCAT_NULL_YIELDS_NULL ON;
	SET ARITHABORT ON;

	IF UPDATE (FK_CORE_DROPDOWNVALUE_SALUTATION) OR UPDATE (INITIALS) OR UPDATE (PREPOSITION) OR UPDATE (LASTNAME) 
    BEGIN
		UPDATE FN SET 
		  FN.FULLNAME_ATTN = ISNULL(LTRIM(RTRIM(CT.[TEXT])) + ' ', '') +
						ISNULL(LTRIM(RTRIM(NULLIF(FN.INITIALS,''))) + ' ', '') + 
						ISNULL(LTRIM(RTRIM(NULLIF(FN.PREPOSITION,''))) + ' ', '') + 
						ISNULL(LTRIM(RTRIM(FN.LASTNAME)),'')
		FROM 
			CRM_CONTACT FN
			LEFT JOIN CORE_DROPDOWNVALUE CD WITH (NOLOCK) ON CD.ID = FN.FK_CORE_DROPDOWNVALUE_SALUTATION
			LEFT JOIN CORE_TRANSLATION CT WITH (NOLOCK) ON CT.FK_CORE_TRANSLATION_KEY = CD.TL_VALUE AND CT.FK_CORE_LANGUAGE = 2 -- Nederlands
		INNER JOIN INSERTED I ON FN.ID = I.ID
	END
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CRM_CONTACT_TS_LASTMODIFIED]
		   ON  [dbo].[CRM_CONTACT]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				CRM_CONTACT  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[CRM_CONTACT] ADD CONSTRAINT [PK_CRM_CONTACT] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRM_CONTACT] ADD CONSTRAINT [FK_CRM_CONTACT_CORE_DROPDOWNVALUE] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_SALUTATION]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CRM_CONTACT] ADD CONSTRAINT [FK_CRM_CONTACT_CORE_DROPDOWNVALUE1] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_GENDER]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CRM_CONTACT] ADD CONSTRAINT [FK_CRM_CONTACT_CORE_DROPDOWNVALUE2] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_ATTN]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CRM_CONTACT] ADD CONSTRAINT [FK_CRM_CONTACT_CRM_RELATION] FOREIGN KEY ([FK_CRM_RELATION]) REFERENCES [dbo].[CRM_RELATION] ([ID])
GO
