CREATE TABLE [dbo].[DOCUMENT_COLLECTION_DOCUMENT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_DOCUMENT_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_DOCUMENT_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_DOCUMENT_ACTIVE] DEFAULT ((1)),
[FK_DOCUMENT_COLLECTION] [int] NULL,
[FK_DOCUMENT] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

				CREATE TRIGGER [dbo].[TR_DOCUMENT_COLLECTION_DOCUMENT_TS_LASTMODIFIED]
						   ON  [dbo].[DOCUMENT_COLLECTION_DOCUMENT]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								DOCUMENT_COLLECTION_DOCUMENT T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[DOCUMENT_COLLECTION_DOCUMENT] ADD CONSTRAINT [PK_DOCUMENT_COLLECTION_DOCUMENT] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOCUMENT_COLLECTION_DOCUMENT] ADD CONSTRAINT [FK_DOCUMENT_COLLECTION_DOCUMENT_DOCUMENT] FOREIGN KEY ([FK_DOCUMENT]) REFERENCES [dbo].[DOCUMENT] ([ID])
GO
ALTER TABLE [dbo].[DOCUMENT_COLLECTION_DOCUMENT] ADD CONSTRAINT [FK_DOCUMENT_COLLECTION_DOCUMENT_DOCUMENT_COLLECTION] FOREIGN KEY ([FK_DOCUMENT_COLLECTION]) REFERENCES [dbo].[DOCUMENT_COLLECTION] ([ID])
GO
