CREATE TABLE [dbo].[DOCUMENT_COLLECTION_CONTACT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_CONTACT_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_CONTACT_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_CONTACT_ACTIVE] DEFAULT ((1)),
[FK_DOCUMENT_COLLECTION] [int] NULL,
[FK_CRM_CONTACT] [int] NULL,
[DOWNLOADED] [bit] NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_CONTACT_DOWNLOADED] DEFAULT ((0)),
[EXPIRATION_DATE] [datetime] NULL CONSTRAINT [DF_DOCUMENT_COLLECTION_CONTACT_EXPIRATION_DATE] DEFAULT (dateadd(day,(7),getdate()))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

				CREATE TRIGGER [dbo].[TR_DOCUMENT_COLLECTION_CONTACT_TS_LASTMODIFIED]
						   ON  [dbo].[DOCUMENT_COLLECTION_CONTACT]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								DOCUMENT_COLLECTION_CONTACT T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[DOCUMENT_COLLECTION_CONTACT] ADD CONSTRAINT [PK_DOCUMENT_COLLECTION_CONTACT] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOCUMENT_COLLECTION_CONTACT] ADD CONSTRAINT [FK_DOCUMENT_COLLECTION_CONTACT_CRM_CONTACT] FOREIGN KEY ([FK_CRM_CONTACT]) REFERENCES [dbo].[CRM_CONTACT] ([ID])
GO
ALTER TABLE [dbo].[DOCUMENT_COLLECTION_CONTACT] ADD CONSTRAINT [FK_DOCUMENT_COLLECTION_CONTACT_DOCUMENT_COLLECTION] FOREIGN KEY ([FK_DOCUMENT_COLLECTION]) REFERENCES [dbo].[DOCUMENT_COLLECTION] ([ID])
GO
