CREATE TABLE [dbo].[CORE_SETTING]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_SETTING_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_SETTING_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_SETTING_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CORE_SETTING_GROUP] [int] NOT NULL,
[FK_CORE_SETTING_TYPE] [int] NOT NULL,
[DESCRIPTION] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REQUIRED] [bit] NULL CONSTRAINT [DF_CORE_SETTING_REQUIRED] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_SETTING_TS_LASTMODIFIED]
	ON  [dbo].[CORE_SETTING]
	AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	UPDATE T SET 
		T.TS_LASTMODIFIED = GETDATE()
	FROM 
		CORE_SETTING T
	INNER JOIN INSERTED I ON T.ID = I.ID
END
GO
ALTER TABLE [dbo].[CORE_SETTING] ADD CONSTRAINT [PK_CORE_SETTING] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_SETTING] ADD CONSTRAINT [FK_CORE_SETTING_CORE_SETTING_GROUP] FOREIGN KEY ([FK_CORE_SETTING_GROUP]) REFERENCES [dbo].[CORE_SETTING_GROUP] ([ID])
GO
ALTER TABLE [dbo].[CORE_SETTING] ADD CONSTRAINT [FK_CORE_SETTING_CORE_SETTING_TYPE] FOREIGN KEY ([FK_CORE_SETTING_TYPE]) REFERENCES [dbo].[CORE_SETTING_TYPE] ([ID])
GO
