CREATE TABLE [dbo].[CORE_ROLE_PERMISSION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_ROLE_PERMISSION_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_ROLE_PERMISSION_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CORE_PERMISSION] [int] NULL,
[FK_CORE_ROLE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_ROLE_PERMISSION] ADD CONSTRAINT [PK_CORE_ROLE_PERMISSION] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_ROLE_PERMISSION] ADD CONSTRAINT [FK_CORE_ROLE_PERMISSION_CORE_PERMISSION] FOREIGN KEY ([FK_CORE_PERMISSION]) REFERENCES [dbo].[CORE_PERMISSION] ([ID])
GO
ALTER TABLE [dbo].[CORE_ROLE_PERMISSION] ADD CONSTRAINT [FK_CORE_ROLE_PERMISSION_CORE_ROLE] FOREIGN KEY ([FK_CORE_ROLE]) REFERENCES [dbo].[CORE_ROLE] ([ID])
GO
