CREATE TABLE [dbo].[CORE_USER_ROLE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_USER_ROLE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_USER_ROLE_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CORE_USER] [int] NULL,
[FK_CORE_ROLE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_USER_ROLE] ADD CONSTRAINT [PK_CORE_USER_ROLE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_USER_ROLE] ADD CONSTRAINT [FK_CORE_USER_ROLE_CORE_USER] FOREIGN KEY ([FK_CORE_USER]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[CORE_USER_ROLE] ADD CONSTRAINT [FK_CORE_USER_ROLE_CORE_USER_ROLE] FOREIGN KEY ([FK_CORE_ROLE]) REFERENCES [dbo].[CORE_ROLE] ([ID])
GO
