CREATE TABLE [dbo].[CORE_USER_CONTRACT_DAYS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_USER_CONTRACT_DAYS_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_USER_CONTRACT_DAYS_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_USER_CONTRACT_DAYS_ACTIVE] DEFAULT ((1)),
[FK_CORE_USER_CONTRACT] [int] NOT NULL,
[DAY] [int] NOT NULL,
[HOURS] [float] NULL,
[EVEN_WEEK] [bit] NULL CONSTRAINT [DF_CORE_USER_CONTRACT_DAYS_ODD] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_USER_CONTRACT_DAYS_TS_LASTMODIFIED]
						   ON  [dbo].[CORE_USER_CONTRACT_DAYS]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								CORE_USER_CONTRACT_DAYS T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[CORE_USER_CONTRACT_DAYS] ADD CONSTRAINT [PK_CORE_USER_CONTRACT_DAYS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_USER_CONTRACT_DAYS] ADD CONSTRAINT [FK_CORE_USER_CONTRACT_DAYS_CORE_USER_CONTRACT] FOREIGN KEY ([FK_CORE_USER_CONTRACT]) REFERENCES [dbo].[CORE_USER_CONTRACT] ([ID])
GO
