CREATE TABLE [dbo].[DOCUMENT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_DOCUMENT_ACTIVE] DEFAULT ((1)),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_DOCUMENT_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_DOCUMENT_TS_LASTMODIFIED] DEFAULT (getdate()),
[SEQUENCE] [float] NULL,
[FK_TABLE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FK_ITEM] [int] NOT NULL,
[TITLE] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FILEPATH] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DIRECTORY] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILETYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FILESIZE] [int] NULL,
[UPLOADER_FK_TABLE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPLOADER_FK_ITEM] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_DOCUMENT_DIRECTORY]
	ON  [dbo].[DOCUMENT]
	AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	IF (TRIGGER_NESTLEVEL() > 1)
		RETURN

	UPDATE T SET 
		T.DIRECTORY = IIF(CHARINDEX('\', REVERSE(T.FILEPATH)) > 0, LEFT(T.FILEPATH, LEN(T.FILEPATH) - (CHARINDEX('\', REVERSE(T.FILEPATH)) -1)), NULL)
	FROM 
		DOCUMENT  T
	INNER JOIN INSERTED I ON T.ID = I.ID
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_DOCUMENT_TS_LASTMODIFIED]
		   ON  [dbo].[DOCUMENT]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				DOCUMENT  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[DOCUMENT] ADD CONSTRAINT [PK_DOCUMENT] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
