CREATE TABLE [dbo].[NOTIFICATION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_COMMUNICATION_NOTIFICATION_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_COMMUNICATION_NOTIFICATION_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_COMMUNICATION_NOTIFICATION_ACTIVE] DEFAULT ((1)),
[RECIPIENT_FK_CORE_USER] [int] NULL,
[DATE] [datetime] NULL,
[SUBJECT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTENT] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_TABLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [int] NULL,
[SOURCE_URL] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[READED] [bit] NULL CONSTRAINT [DF_NOTIFICATION_READED] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_NOTIFICATION_TS_LASTMODIFIED]
						   ON  [dbo].[NOTIFICATION]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								[NOTIFICATION] T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD CONSTRAINT [PK_COMMUNICATION_NOTIFICATION] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD CONSTRAINT [FK_NOTIFICATION_CORE_USER] FOREIGN KEY ([RECIPIENT_FK_CORE_USER]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
