CREATE TABLE [dbo].[TASK_USER_CUSTOM_MAP]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FK_USER_CUSTOM_MAP] [int] NULL,
[FK_TASK] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_USER_CUSTOM_MAP] ADD CONSTRAINT [PK_TASK_USER_CUSTOM_GROUP] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_USER_CUSTOM_MAP] ADD CONSTRAINT [FK_TASK_USER_CUSTOM_GROUP_TASK_USER_CUSTOM_GROUP] FOREIGN KEY ([FK_TASK]) REFERENCES [dbo].[TASK] ([ID])
GO
ALTER TABLE [dbo].[TASK_USER_CUSTOM_MAP] ADD CONSTRAINT [FK_TASK_USER_CUSTOM_GROUP_USER_CUSTOM_MAP] FOREIGN KEY ([FK_USER_CUSTOM_MAP]) REFERENCES [dbo].[USER_CUSTOM_MAP] ([ID])
GO
