CREATE TABLE [dbo].[CRM_CONTACT_LANGUAGE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CRM_CONTACT_LANGUAGE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CRM_CONTACT_LANGUAGE_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CRM_CONTACT] [int] NOT NULL,
[FK_CORE_LANGUAGE] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CRM_CONTACT_LANGUAGE_TS_LASTMODIFIED]
		   ON  [dbo].[CRM_CONTACT_LANGUAGE]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				CRM_CONTACT_LANGUAGE  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[CRM_CONTACT_LANGUAGE] ADD CONSTRAINT [PK_CRM_CONTACT_LANGUAGE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRM_CONTACT_LANGUAGE] ADD CONSTRAINT [FK_CRM_CONTACT_LANGUAGE_CORE_LANGUAGE] FOREIGN KEY ([FK_CORE_LANGUAGE]) REFERENCES [dbo].[CORE_LANGUAGE] ([ID])
GO
ALTER TABLE [dbo].[CRM_CONTACT_LANGUAGE] ADD CONSTRAINT [FK_CRM_CONTACT_LANGUAGE_CRM_CONTACT] FOREIGN KEY ([FK_CRM_CONTACT]) REFERENCES [dbo].[CRM_CONTACT] ([ID])
GO
