CREATE TABLE [dbo].[FINANCE_INVOICE_SCHEME]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_FINANCE_INVOICE_SCHEME_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_FINANCE_INVOICE_SCHEME_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_FINANCE_INVOICE_SCHEME_ACTIVE] DEFAULT ((1)),
[FK_ASSORTMENT_PRODUCT] [int] NULL,
[FK_PROJECT_ASSORTMENT_PRODUCT] [int] NULL,
[FK_FINANCE_INVOICE_LINE] [int] NULL,
[DAYS] [int] NULL,
[DATE] [datetime] NULL,
[PERCENTAGE] [decimal] (15, 6) NULL,
[AUTOMATIC_REMNANT] [bit] NULL CONSTRAINT [DF_FINANCE_INVOICE_SCHEME_AUTOMATIC] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_FINANCE_INVOICE_SCHEME_TS_LASTMODIFIED]
						   ON  [dbo].[FINANCE_INVOICE_SCHEME]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								FINANCE_INVOICE_SCHEME T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[FINANCE_INVOICE_SCHEME] ADD CONSTRAINT [PK_FINANCE_INVOICE_SCHEME] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FINANCE_INVOICE_SCHEME] ADD CONSTRAINT [FK_FINANCE_INVOICE_SCHEME_ASSORTMENT_PRODUCT] FOREIGN KEY ([FK_ASSORTMENT_PRODUCT]) REFERENCES [dbo].[ASSORTMENT_PRODUCT] ([ID])
GO
ALTER TABLE [dbo].[FINANCE_INVOICE_SCHEME] ADD CONSTRAINT [FK_FINANCE_INVOICE_SCHEME_FINANCE_INVOICE_LINE] FOREIGN KEY ([FK_FINANCE_INVOICE_LINE]) REFERENCES [dbo].[FINANCE_INVOICE_LINE] ([ID])
GO
ALTER TABLE [dbo].[FINANCE_INVOICE_SCHEME] ADD CONSTRAINT [FK_FINANCE_INVOICE_SCHEME_PROJECT_ASSORTMENT_PRODUCT] FOREIGN KEY ([FK_PROJECT_ASSORTMENT_PRODUCT]) REFERENCES [dbo].[PROJECT_ASSORTMENT_PRODUCT] ([ID])
GO
