CREATE TABLE [dbo].[TASK_SUBSCRIPTION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_TASK_SUBSCRIPTION_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_TASK_SUBSCRIPTION_TS_LASTMODIFIED] DEFAULT (getdate()),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_TASK_SUBSCRIPTION_ACTIVE] DEFAULT ((1)),
[FK_CORE_USER] [int] NULL,
[FK_TASK] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

				CREATE TRIGGER [dbo].[TR_TASK_SUBSCRIPTION_TS_LASTMODIFIED]
						   ON  [dbo].[TASK_SUBSCRIPTION]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								TASK_SUBSCRIPTION T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[TASK_SUBSCRIPTION] ADD CONSTRAINT [PK_TASK_SUBSCRIPTION] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_SUBSCRIPTION] ADD CONSTRAINT [FK_TASK_SUBSCRIPTION_CORE_USER] FOREIGN KEY ([FK_CORE_USER]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
ALTER TABLE [dbo].[TASK_SUBSCRIPTION] ADD CONSTRAINT [FK_TASK_SUBSCRIPTION_TASK] FOREIGN KEY ([FK_TASK]) REFERENCES [dbo].[TASK] ([ID])
GO
