CREATE TABLE [dbo].[CORE_PERMISSION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_PERMISSION_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_PERMISSION_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_PERMISSION_TS_LASTMODIFIED] DEFAULT (getdate()),
[DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_PERMISSION] ADD CONSTRAINT [PK_CORE_PERMISSION] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
