CREATE TABLE [dbo].[USER_CUSTOM_MAP]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FK_CORE_USER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_CUSTOM_MAP] ADD CONSTRAINT [PK_USER_CUSTOM_MAP] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_CUSTOM_MAP] ADD CONSTRAINT [FK_USER_CUSTOM_MAP_CORE_USER] FOREIGN KEY ([FK_CORE_USER]) REFERENCES [dbo].[CORE_USER] ([ID])
GO
