CREATE TABLE [dbo].[DOCUMENT_FILETYPE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FILETYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOCUMENT_FILETYPE] ADD CONSTRAINT [PK_DOCUMENT_FILETYPE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
