CREATE TABLE [dbo].[TASK_FILTER]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FK_TASK] [int] NOT NULL,
[FK_CORE_DROPDOWNVALUE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_FILTER] ADD CONSTRAINT [PK_TASK_FILTER] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_FILTER] ADD CONSTRAINT [FK_TASK_FILTER_CORE_DROPDOWNVALUE] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
