CREATE TABLE [dbo].[CORE_USER]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_USERS_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_USERS_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_USERS_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CORE_ADDRESS] [int] NULL,
[FK_CORE_DROPDOWNVALUE_POSITION] [int] NULL,
[FK_CORE_DROPDOWNVALUE_DEPARTMENT] [int] NULL,
[FK_CORE_DROPDOWNVALUE_GENDER] [int] NULL,
[FK_CORE_ROLE_NOTIFICATION] [int] NULL,
[LOGIN_ENABLED] [bit] NULL CONSTRAINT [DF_CORE_USER_CANLOGIN] DEFAULT ((0)),
[EMAILADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PASSWORD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMEMBER_TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREPOSITION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULLNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE_MOBILE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE_EMERGENCY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_OF_BIRTH] [datetime] NULL,
[REMARKS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHOTO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXCLUDE_PAYMENT] [bit] NULL CONSTRAINT [DF_CORE_USER_EXCLUDE_PAY] DEFAULT ((0)),
[USERCODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZZP] [bit] NULL CONSTRAINT [DF_CORE_USER_ZZP] DEFAULT ((0)),
[RECEIVE_NOTIFICATION] [bit] NULL CONSTRAINT [DF_CORE_USER_RECEIVE_NOTIFICATION] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_USER_FULLNAME]
		   ON  [dbo].[CORE_USER]
		   AFTER UPDATE, INSERT
		AS 
		BEGIN
			SET NOCOUNT ON;

	IF UPDATE (FIRSTNAME) OR UPDATE (PREPOSITION) OR UPDATE (LASTNAME) 
    BEGIN
		UPDATE FN SET 
			FN.FULLNAME = (
						ISNULL(LTRIM(RTRIM(NULLIF(FN.FIRSTNAME,'')))+' ','') + 
						CASE WHEN LEN(LTRIM(RTRIM(FN.PREPOSITION))) > '' THEN
								ISNULL(LTRIM(RTRIM(FN.PREPOSITION)) + ' ', '')	
						ELSE
							''
						END +
						ISNULL(LTRIM(RTRIM(FN.LASTNAME)),'')				
			)
		FROM 
			CORE_USER  FN
		INNER JOIN INSERTED I ON FN.ID = I.ID
	END
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CORE_USER_TS_LASTMODIFIED]
		   ON  [dbo].[CORE_USER]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			UPDATE T SET 
				T.TS_LASTMODIFIED = GETDATE()
			FROM 
				CORE_USER  T
			INNER JOIN INSERTED I ON T.ID = I.ID
		END
GO
ALTER TABLE [dbo].[CORE_USER] ADD CONSTRAINT [PK_CORE_USERS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_USER] ADD CONSTRAINT [FK_CORE_USER_CORE_ADDRESS] FOREIGN KEY ([FK_CORE_ADDRESS]) REFERENCES [dbo].[CORE_ADDRESS] ([ID])
GO
ALTER TABLE [dbo].[CORE_USER] ADD CONSTRAINT [FK_CORE_USER_CORE_DROPDOWNVALUE] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_POSITION]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CORE_USER] ADD CONSTRAINT [FK_CORE_USER_CORE_DROPDOWNVALUE1] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_DEPARTMENT]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CORE_USER] ADD CONSTRAINT [FK_CORE_USER_CORE_DROPDOWNVALUE2] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_GENDER]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CORE_USER] ADD CONSTRAINT [FK_CORE_USER_CORE_ROLE] FOREIGN KEY ([FK_CORE_ROLE_NOTIFICATION]) REFERENCES [dbo].[CORE_ROLE] ([ID])
GO
