CREATE TABLE [dbo].[CRM_RELATION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CRM_RELATION_ACTIVE] DEFAULT ((1)),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CRM_RELATION_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CRM_RELATION_TS_LASTMODIFIED] DEFAULT (getdate()),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PHONENUMBER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAILADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FK_CRM_CONTACT_FINANCE] [int] NULL,
[FK_CORE_DROPDOWNVALUE_INDUSTRY] [int] NULL,
[FK_CORE_DROPDOWNVALUE_SEGMENTATION] [int] NULL,
[FK_CORE_DROPDOWNVALUE_RELATIONTYPE] [int] NULL,
[FK_CORE_LABEL] [int] NULL,
[FK_FINANCE_INVOICE_COLLECT_INTERVAL] [int] NULL,
[REMARKS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VAT_LIABLE] [bit] NULL CONSTRAINT [DF_CRM_RELATION_VAT_LIABLE] DEFAULT ((1)),
[VAT_NUMBER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVOICE_ELECTRONIC] [bit] NULL CONSTRAINT [DF_CRM_RELATION_INVOICING_ELECTRONIC] DEFAULT ((1)),
[RATE_KM] [decimal] (30, 15) NULL,
[SINGED_DATAPROCESSINGAGREEMENT] [bit] NULL,
[NUMBER_DEBTOR] [int] NULL,
[NUMBER_CREDITOR] [int] NULL,
[NUMBER_BANK] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILLABLE] [bit] NULL CONSTRAINT [DF_CRM_RELATION_BILLABLE] DEFAULT ((1)),
[PAYABLE] [bit] NULL CONSTRAINT [DF_CRM_RELATION_PAYABLE] DEFAULT ((1)),
[EXACT_DEBTOR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXACT_DEBTOR_LASTSYNC] [datetime] NULL,
[EXACT_DEBTOR_ERROR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXACT_CREDITOR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXACT_CREDITOR_LASTSYNC] [datetime] NULL,
[EXACT_CREDITOR_ERROR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_CRM_RELATION_TS_LASTMODIFIED]
		   ON  [dbo].[CRM_RELATION]
		   AFTER UPDATE
		AS 
		BEGIN
			SET NOCOUNT ON;

			IF (
				NOT UPDATE(EXACT_DEBTOR_ID) AND 
				NOT UPDATE(EXACT_DEBTOR_LASTSYNC) AND 
				NOT UPDATE(EXACT_DEBTOR_ERROR) AND
				NOT UPDATE(EXACT_CREDITOR_ID) AND 
				NOT UPDATE(EXACT_CREDITOR_LASTSYNC) AND 
				NOT UPDATE(EXACT_CREDITOR_ERROR)
			)
			BEGIN

				UPDATE T SET 
					T.TS_LASTMODIFIED = GETDATE()
				FROM 
					CRM_RELATION  T
				INNER JOIN INSERTED I ON T.ID = I.ID

			END
		END
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [PK_CRM_RELATION] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [FK_CRM_RELATION_CORE_DROPDOWNVALUE2] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_INDUSTRY]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [FK_CRM_RELATION_CORE_DROPDOWNVALUE3] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_SEGMENTATION]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [FK_CRM_RELATION_CORE_DROPDOWNVALUE4] FOREIGN KEY ([FK_CORE_DROPDOWNVALUE_RELATIONTYPE]) REFERENCES [dbo].[CORE_DROPDOWNVALUE] ([ID])
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [FK_CRM_RELATION_CORE_LABEL] FOREIGN KEY ([FK_CORE_LABEL]) REFERENCES [dbo].[CORE_LABEL] ([ID])
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [FK_CRM_RELATION_CRM_CONTACT] FOREIGN KEY ([FK_CRM_CONTACT_FINANCE]) REFERENCES [dbo].[CRM_CONTACT] ([ID])
GO
ALTER TABLE [dbo].[CRM_RELATION] ADD CONSTRAINT [FK_CRM_RELATION_FINANCE_INVOICE_COLLECT_INTERVAL] FOREIGN KEY ([FK_FINANCE_INVOICE_COLLECT_INTERVAL]) REFERENCES [dbo].[FINANCE_INVOICE_COLLECT_INTERVAL] ([ID])
GO
