CREATE TABLE [dbo].[PROJECT_ASSORTMENT_PRODUCT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_PROJECT_ASSORTMENT_PRODUC_ACTIVE] DEFAULT ((1)),
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_PROJECT_ASSORTMENT_PRODUC_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_PROJECT_ASSORTMENT_PRODUC_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_PROJECT] [int] NULL,
[FK_ASSORTMENT_PRODUCT] [int] NULL,
[FK_CRM_RELATION] [int] NULL,
[QUANTITY] [int] NULL,
[PRICE] [decimal] (15, 6) NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TR_PROJECT_ASSORTMENT_PRODUCT_TS_LASTMODIFIED]
						   ON  [dbo].[PROJECT_ASSORTMENT_PRODUCT]
						   AFTER UPDATE
						AS 
						BEGIN
							SET NOCOUNT ON;

							UPDATE T SET 
								T.TS_LASTMODIFIED = GETDATE()
							FROM 
								PROJECT_ASSORTMENT_PRODUCT T
							INNER JOIN INSERTED I ON T.ID = I.ID
						END
GO
ALTER TABLE [dbo].[PROJECT_ASSORTMENT_PRODUCT] ADD CONSTRAINT [PK_PROJECT_ASSORTMENT_PRODUC] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROJECT_ASSORTMENT_PRODUCT] ADD CONSTRAINT [FK_PROJECT_ASSORTMENT_PRODUCT_PROJECT] FOREIGN KEY ([FK_PROJECT]) REFERENCES [dbo].[PROJECT] ([ID])
GO
ALTER TABLE [dbo].[PROJECT_ASSORTMENT_PRODUCT] ADD CONSTRAINT [FK_PROJECT_ASSORTMENT_PRODUCT_PROJECT_ASSORTMENT_PRODUCT] FOREIGN KEY ([FK_ASSORTMENT_PRODUCT]) REFERENCES [dbo].[ASSORTMENT_PRODUCT] ([ID])
GO
