CREATE TABLE [dbo].[CORE_SETTING_VALUE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CORE_SETTING_VALUE_ACTIVE] DEFAULT ((1)),
[SEQUENCE] [float] NULL,
[TS_CREATED] [datetime] NOT NULL CONSTRAINT [DF_CORE_SETTING_VALUE_TS_CREATED] DEFAULT (getdate()),
[TS_LASTMODIFIED] [datetime] NULL CONSTRAINT [DF_CORE_SETTING_VALUE_TS_LASTMODIFIED] DEFAULT (getdate()),
[FK_CORE_SETTING] [int] NOT NULL,
[FK_CORE_SETTING_ALLOWED_VALUE] [int] NULL,
[VALUE_UNCONSTRAINED] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[TR_CORE_SETTING_VALUE_TS_LASTMODIFIED]
	ON  [dbo].[CORE_SETTING_VALUE]
	AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	UPDATE T SET 
		T.TS_LASTMODIFIED = GETDATE()
	FROM 
		CORE_SETTING_VALUE T
	INNER JOIN INSERTED I ON T.ID = I.ID
END
GO
ALTER TABLE [dbo].[CORE_SETTING_VALUE] ADD CONSTRAINT [PK_CORE_SETTING_VALUE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CORE_SETTING_VALUE] ADD CONSTRAINT [FK_CORE_SETTING_VALUE_CORE_SETTING] FOREIGN KEY ([FK_CORE_SETTING]) REFERENCES [dbo].[CORE_SETTING] ([ID])
GO
ALTER TABLE [dbo].[CORE_SETTING_VALUE] ADD CONSTRAINT [FK_CORE_SETTING_VALUE_CORE_SETTING_ALLOWED_VALUE] FOREIGN KEY ([FK_CORE_SETTING_ALLOWED_VALUE]) REFERENCES [dbo].[CORE_SETTING_ALLOWED_VALUE] ([ID])
GO
