<?php

return [
    // GLOBAL
    'AANTAL_DAGEN_VERJAARDAG_NOTIFICATIE' => 8,
    'EMAIL_TESTMODE' => 9,
    'EMAIL_TEST_EMAIL' => 10,

    // ACCOUNTANCY
    'EXACT_AUTHORIZATION_CODE' => 4,
    'EXACT_ACCESS_TOKEN' => 5,
    'EXACT_REFRESH_TOKEN' => 6,
    'EXACT_EXPIRES_IN' => 7,
];